import { createClient } from '@supabase/supabase-js';
import { NextResponse } from 'next/server';

// ============================================================
// SEED CONTENT API ROUTE
// Inserts all mock data into Supabase tables using service_role
// Safe to run multiple times (uses upsert)
// ============================================================

const FALLBACK_IMAGES = {
  producerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&q=80',
  producerCover: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&h=600&fit=crop&q=80',
  tutorialCover: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=450&fit=crop&q=80',
  beatCover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=800&fit=crop&q=80',
  gearCover: 'https://images.unsplash.com/photo-1558383409-57baa6c8b082?w=800&h=450&fit=crop&q=80',
  samplePackCover: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=800&h=800&fit=crop&q=80',
  artistAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600',
  artistCover: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1600',
};

// ======================== PRODUCERS DATA ========================

const producers = [
  {
    id: 'p1',
    name: 'KVNG Beats',
    slug: 'kvng-beats',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&h=600&fit=crop&q=80',
    bio: 'Multi-platinum producer from Atlanta. Known for dark trap instrumentals with signature 808 patterns. Produced for Future, Young Thug, and Gunna. FL Studio wizard with 10+ years of experience crafting hits that dominate the charts.',
    location: 'Atlanta, GA',
    daws: ['FL Studio'],
    genres: ['Trap', 'Dark Trap', 'Hip-Hop'],
    credits: ['Future - "Mask Off" (co-prod)', 'Young Thug - "Hot"', 'Gunna - "Pushin P" (add. prod)', 'Lil Baby - "Real As It Gets"'],
    beat_count: 342,
    follower_count: 45200,
    links: { instagram: 'https://instagram.com/kvngbeats', youtube: 'https://youtube.com/@kvngbeats', beatstars: 'https://beatstars.com/kvngbeats' },
    featured: true,
    joined_at: '2023-06-15T00:00:00Z',
    status: 'published',
  },
  {
    id: 'p2',
    name: 'Synthia Rose',
    slug: 'synthia-rose',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&h=600&fit=crop&q=80',
    bio: 'R&B and neo-soul producer blending vintage synths with modern production. Ableton Live specialist with a background in jazz piano. Her beats have been placed on major playlists and featured in Netflix originals.',
    location: 'Los Angeles, CA',
    daws: ['Ableton Live', 'Logic Pro'],
    genres: ['R&B', 'Neo-Soul', 'Lo-Fi'],
    credits: ['SZA - "Good Days" (add. keys)', 'Daniel Caesar - session musician', 'H.E.R. - "Focus" (remix)', 'Jorja Smith - "Blue Lights" (flip)'],
    beat_count: 189,
    follower_count: 28400,
    links: { instagram: 'https://instagram.com/synthiarose', spotify: 'https://open.spotify.com/artist/synthiarose', soundcloud: 'https://soundcloud.com/synthiarose', website: 'https://synthiarose.com' },
    featured: true,
    joined_at: '2023-08-22T00:00:00Z',
    status: 'published',
  },
  {
    id: 'p3',
    name: 'DrumGod',
    slug: 'drumgod',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=1200&h=600&fit=crop&q=80',
    bio: 'Drum pattern specialist and sound designer. Known for intricate hi-hat patterns and punchy drum kits. Has released 20+ drum kits downloaded over 500K times. Regular contributor to Splice and BeatStars.',
    location: 'Chicago, IL',
    daws: ['FL Studio', 'MPC Software'],
    genres: ['Drill', 'Trap', 'Boom Bap'],
    credits: ['Chief Keef - drum programming', 'Polo G - "Rapstar" (drums)', 'Lil Durk - "All My Life" (perc)', 'G Herbo - session work'],
    beat_count: 567,
    follower_count: 72100,
    links: { youtube: 'https://youtube.com/@drumgod', beatstars: 'https://beatstars.com/drumgod', twitter: 'https://twitter.com/drumgodbeats' },
    featured: true,
    joined_at: '2023-03-10T00:00:00Z',
    status: 'published',
  },
  {
    id: 'p4',
    name: 'Melo Circuit',
    slug: 'melo-circuit',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&h=600&fit=crop&q=80',
    bio: 'Melodic trap and ambient producer pushing the boundaries of what beats can sound like. Logic Pro user with a love for cinematic sound design. His signature pads and atmospheric textures have defined a new wave of emotional trap.',
    location: 'Toronto, ON',
    daws: ['Logic Pro', 'Ableton Live'],
    genres: ['Melodic Trap', 'Ambient', 'Cinematic'],
    credits: ['Drake - "Fair Trade" (add. prod)', 'The Weeknd - session work', 'PartyNextDoor - "Loyal" (co-prod)', 'NAV - background vocals'],
    beat_count: 234,
    follower_count: 38900,
    links: { instagram: 'https://instagram.com/melocircuit', spotify: 'https://open.spotify.com/artist/melocircuit', youtube: 'https://youtube.com/@melocircuit' },
    featured: true,
    joined_at: '2023-05-01T00:00:00Z',
    status: 'published',
  },
  {
    id: 'p5',
    name: 'Bass Architect',
    slug: 'bass-architect',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1200&h=600&fit=crop&q=80',
    bio: 'Sound designer and bass music specialist. Crafts heavy 808s and sub-bass patches from scratch using synthesis. Known for making the hardest-hitting low end in the game. Runs a popular YouTube channel with 200K+ subscribers.',
    location: 'Houston, TX',
    daws: ['FL Studio', 'Ableton Live'],
    genres: ['Trap', 'Phonk', 'Bass Music'],
    credits: ['Travis Scott - "SICKO MODE" (808 design)', 'Don Toliver - mixing', 'Megan Thee Stallion - "Savage" (bass)', 'Sauce Walka - production'],
    beat_count: 412,
    follower_count: 91300,
    links: { youtube: 'https://youtube.com/@bassarchitect', twitter: 'https://twitter.com/bassarchitect', website: 'https://bassarchitect.com' },
    featured: true,
    joined_at: '2023-01-20T00:00:00Z',
    status: 'published',
  },
  {
    id: 'p6',
    name: 'Kira Voltage',
    slug: 'kira-voltage',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1571266028243-d220c6d3173e?w=1200&h=600&fit=crop&q=80',
    bio: 'Electronic and experimental producer merging EDM with hip-hop. Ableton Push 3 power user. Her live performance sets have been featured at SXSW, A3C, and Rolling Loud. Also runs production workshops for women in music.',
    location: 'Miami, FL',
    daws: ['Ableton Live'],
    genres: ['Electronic', 'Experimental', 'Future Bass'],
    credits: ['Skrillex - remix collab', 'Rico Nasty - "Smack a Bitch" (remix)', 'Charli XCX - session synths', 'Diplo - "Lean On" (bootleg)'],
    beat_count: 156,
    follower_count: 34700,
    links: { instagram: 'https://instagram.com/kiravoltage', soundcloud: 'https://soundcloud.com/kiravoltage', spotify: 'https://open.spotify.com/artist/kiravoltage' },
    featured: false,
    joined_at: '2023-09-12T00:00:00Z',
    status: 'published',
  },
  {
    id: 'p7',
    name: 'OG Sampler',
    slug: 'og-sampler',
    avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=400&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=1200&h=600&fit=crop&q=80',
    bio: 'Old school meets new school. Sample-based producer with an encyclopedic knowledge of vinyl. Known for flipping obscure soul, jazz, and funk records into modern bangers. MPC Live II is his weapon of choice.',
    location: 'New York, NY',
    daws: ['MPC Software', 'Pro Tools'],
    genres: ['Boom Bap', 'Jazz Rap', 'Sample-Based'],
    credits: ['Joey Bada$$ - "Devastated" (sample)', 'J. Cole - "No Role Modelz" (add. chop)', 'Rapsody - production credits', 'Black Thought - beat tape'],
    beat_count: 289,
    follower_count: 52400,
    links: { instagram: 'https://instagram.com/ogsampler', youtube: 'https://youtube.com/@ogsampler', beatstars: 'https://beatstars.com/ogsampler' },
    featured: true,
    joined_at: '2023-02-14T00:00:00Z',
    status: 'published',
  },
  {
    id: 'p8',
    name: 'Nebula Keys',
    slug: 'nebula-keys',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=400&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=1200&h=600&fit=crop&q=80',
    bio: 'Keyboard player turned producer. Creates lush, keys-driven beats with complex chord progressions. Known for teaching music theory to producers through his viral TikTok series "Chords That Hit Different."',
    location: 'Nashville, TN',
    daws: ['Logic Pro', 'Ableton Live'],
    genres: ['R&B', 'Pop', 'Gospel Trap'],
    credits: ['Chris Brown - session keys', 'Khalid - "Talk" (add. keys)', 'Summer Walker - "Playing Games" (co-prod)', 'Kirk Franklin - remix'],
    beat_count: 198,
    follower_count: 41200,
    links: { instagram: 'https://instagram.com/nebulakeys', youtube: 'https://youtube.com/@nebulakeys', spotify: 'https://open.spotify.com/artist/nebulakeys', website: 'https://nebulakeys.com' },
    featured: false,
    joined_at: '2023-07-30T00:00:00Z',
    status: 'published',
  },
  {
    id: 'p9',
    name: 'Phantom 808',
    slug: 'phantom-808',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&h=600&fit=crop&q=80',
    bio: 'Anonymous producer collective known for dark, atmospheric trap beats. Their identity remains a mystery but their sound is unmistakable — haunting melodies, thunderous 808s, and eerie vocal chops that have dominated SoundCloud and streaming platforms.',
    location: 'Unknown',
    daws: ['FL Studio'],
    genres: ['Dark Trap', 'Phonk', 'Memphis Rap'],
    credits: ['Playboi Carti - type beats', 'Denzel Curry - "Ultimate" (style)', 'XXXTentacion - influence', 'Bones - TeamSESH collabs'],
    beat_count: 723,
    follower_count: 118500,
    links: { soundcloud: 'https://soundcloud.com/phantom808', beatstars: 'https://beatstars.com/phantom808' },
    featured: true,
    joined_at: '2023-01-01T00:00:00Z',
    status: 'published',
  },
  {
    id: 'p10',
    name: 'Luna Waves',
    slug: 'luna-waves',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&q=80',
    cover_image: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=1200&h=600&fit=crop&q=80',
    bio: 'Lo-fi and chill producer creating beats for study sessions and late-night vibes. Her sound is warm, nostalgic, and textured with vinyl crackle, soft piano, and jazzy guitar loops. Has accumulated over 50M streams across lo-fi playlists.',
    location: 'Portland, OR',
    daws: ['Ableton Live', 'FL Studio'],
    genres: ['Lo-Fi', 'Chill Hop', 'Jazz Hop'],
    credits: ['ChilledCow playlist feature', 'College Music collab', 'Lofi Girl official playlist', 'Spotify "Lo-Fi Beats" editorial'],
    beat_count: 445,
    follower_count: 67800,
    links: { spotify: 'https://open.spotify.com/artist/lunawaves', instagram: 'https://instagram.com/lunawaves', youtube: 'https://youtube.com/@lunawaves' },
    featured: false,
    joined_at: '2023-04-18T00:00:00Z',
    status: 'published',
  },
];

// ======================== TUTORIALS DATA ========================

const tutorials = [
  {
    id: 't1',
    title: 'How to Make Hard-Hitting 808s in FL Studio from Scratch',
    slug: 'hard-hitting-808s-fl-studio',
    excerpt: "Learn how to synthesize, layer, and process 808 bass sounds that rattle speakers. No samples needed — we're building from a sine wave.",
    body: 'Full tutorial content here...',
    cover_image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=450&fit=crop&q=80',
    daw: 'FL Studio',
    skill_level: 'Intermediate',
    category: 'Sound Design',
    duration: '18 min',
    producer_id: 'p5',
    tags: ['808', 'bass', 'sound design', 'FL Studio', 'synthesis'],
    view_count: 124500,
    like_count: 8900,
    published_at: '2024-12-01T10:00:00Z',
    status: 'published',
  },
  {
    id: 't2',
    title: "Ableton Live: Creating Lush Pads with Wavetable Synthesis",
    slug: 'ableton-wavetable-pads',
    excerpt: "Deep dive into Ableton's Wavetable synth to create evolving, cinematic pads perfect for melodic trap and ambient production.",
    body: 'Full tutorial content here...',
    cover_image: 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800&h=450&fit=crop&q=80',
    daw: 'Ableton Live',
    skill_level: 'Advanced',
    category: 'Synthesis',
    duration: '24 min',
    producer_id: 'p6',
    tags: ['wavetable', 'pads', 'ableton', 'synthesis', 'ambient'],
    view_count: 67300,
    like_count: 5200,
    published_at: '2024-11-28T10:00:00Z',
    status: 'published',
  },
  {
    id: 't3',
    title: "Beginner's Guide to Mixing Trap Beats — EQ, Compression & More",
    slug: 'beginners-guide-mixing-trap',
    excerpt: "Your first mix doesn't have to sound amateur. Learn the fundamentals of EQ, compression, and gain staging for clean trap mixes.",
    body: 'Full tutorial content here...',
    cover_image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&h=450&fit=crop&q=80',
    daw: 'FL Studio',
    skill_level: 'Beginner',
    category: 'Mixing',
    duration: '32 min',
    producer_id: 'p1',
    tags: ['mixing', 'EQ', 'compression', 'beginner', 'trap'],
    view_count: 234100,
    like_count: 18400,
    published_at: '2024-11-25T10:00:00Z',
    status: 'published',
  },
  {
    id: 't4',
    title: 'Logic Pro X: Advanced Vocal Chain for Professional Results',
    slug: 'logic-pro-vocal-chain',
    excerpt: 'Build a complete vocal processing chain in Logic Pro using stock plugins. From de-essing to parallel compression, get radio-ready vocals.',
    body: 'Full tutorial content here...',
    cover_image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800&h=450&fit=crop&q=80',
    daw: 'Logic Pro',
    skill_level: 'Advanced',
    category: 'Vocal Production',
    duration: '28 min',
    producer_id: 'p8',
    tags: ['vocals', 'mixing', 'logic pro', 'compression', 'chain'],
    view_count: 89200,
    like_count: 6700,
    published_at: '2024-11-22T10:00:00Z',
    status: 'published',
  },
  {
    id: 't5',
    title: 'The Art of Sampling: Chopping Soul Records on the MPC',
    slug: 'sampling-soul-records-mpc',
    excerpt: 'Learn the classic art of sampling — from digging in crates to chopping and flipping soul, jazz, and funk records on the MPC.',
    body: 'Full tutorial content here...',
    cover_image: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=800&h=450&fit=crop&q=80',
    daw: 'MPC Software',
    skill_level: 'Intermediate',
    category: 'Sampling',
    duration: '22 min',
    producer_id: 'p7',
    tags: ['sampling', 'MPC', 'soul', 'vinyl', 'chopping'],
    view_count: 156700,
    like_count: 12300,
    published_at: '2024-11-19T10:00:00Z',
    status: 'published',
  },
  {
    id: 't6',
    title: "Music Theory for Producers: Chord Progressions That Hit Different",
    slug: 'music-theory-chord-progressions',
    excerpt: "You don't need a music degree. Learn the chord progressions behind the biggest hits — minor 7ths, suspended chords, and modal interchange.",
    body: 'Full tutorial content here...',
    cover_image: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800&h=450&fit=crop&q=80',
    daw: 'Ableton Live',
    skill_level: 'Beginner',
    category: 'Music Theory',
    duration: '20 min',
    producer_id: 'p8',
    tags: ['music theory', 'chords', 'harmony', 'beginner', 'keys'],
    view_count: 312400,
    like_count: 24100,
    published_at: '2024-11-16T10:00:00Z',
    status: 'published',
  },
  {
    id: 't7',
    title: 'FL Studio: Advanced Hi-Hat Programming for Drill & Trap',
    slug: 'fl-studio-hihat-programming',
    excerpt: 'Master the art of intricate hi-hat rolls, velocity modulation, and ghost notes. Learn patterns from Metro Boomin, Wheezy, and TM88.',
    body: 'Full tutorial content here...',
    cover_image: 'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=800&h=450&fit=crop&q=80',
    daw: 'FL Studio',
    skill_level: 'Advanced',
    category: 'Beat Making',
    duration: '16 min',
    producer_id: 'p3',
    tags: ['hi-hats', 'drill', 'trap', 'drums', 'programming'],
    view_count: 198300,
    like_count: 15600,
    published_at: '2024-11-13T10:00:00Z',
    status: 'published',
  },
  {
    id: 't8',
    title: 'Mastering Your Own Beats: A Complete Guide for Home Studios',
    slug: 'mastering-home-studio-guide',
    excerpt: 'Professional mastering at home is possible. Learn LUFS targets, multiband compression, stereo imaging, and limiter settings for streaming.',
    body: 'Full tutorial content here...',
    cover_image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&h=450&fit=crop&q=80',
    daw: 'Logic Pro',
    skill_level: 'Advanced',
    category: 'Mastering',
    duration: '35 min',
    producer_id: 'p4',
    tags: ['mastering', 'LUFS', 'limiter', 'home studio', 'streaming'],
    view_count: 143800,
    like_count: 11200,
    published_at: '2024-11-10T10:00:00Z',
    status: 'published',
  },
  {
    id: 't9',
    title: "Creating Lo-Fi Textures: Vinyl Crackle, Tape Saturation & More",
    slug: 'lofi-textures-vinyl-tape',
    excerpt: 'The secret sauce behind lo-fi production — learn how to add warmth, character, and nostalgia to your beats with analog emulation.',
    body: 'Full tutorial content here...',
    cover_image: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&h=450&fit=crop&q=80',
    daw: 'Ableton Live',
    skill_level: 'Intermediate',
    category: 'Sound Design',
    duration: '19 min',
    producer_id: 'p10',
    tags: ['lo-fi', 'texture', 'vinyl', 'tape', 'analog'],
    view_count: 87600,
    like_count: 7400,
    published_at: '2024-11-07T10:00:00Z',
    status: 'published',
  },
  {
    id: 't10',
    title: 'Arrangement Secrets: How to Turn a 4-Bar Loop into a Full Song',
    slug: 'arrangement-loop-to-song',
    excerpt: 'Stop making 4-bar loops that go nowhere. Learn the arrangement techniques pros use to build energy, create transitions, and tell a story.',
    body: 'Full tutorial content here...',
    cover_image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=450&fit=crop&q=80',
    daw: 'FL Studio',
    skill_level: 'Beginner',
    category: 'Arrangement',
    duration: '25 min',
    producer_id: 'p1',
    tags: ['arrangement', 'song structure', 'transitions', 'drops', 'builds'],
    view_count: 267900,
    like_count: 21300,
    published_at: '2024-11-04T10:00:00Z',
    status: 'published',
  },
  {
    id: 't11',
    title: 'Pro Tools Workflow: Recording & Editing Vocals Like a Pro',
    slug: 'pro-tools-vocal-recording',
    excerpt: 'Industry-standard vocal recording techniques in Pro Tools. From mic setup and gain staging to comping, tuning, and alignment.',
    body: 'Full tutorial content here...',
    cover_image: 'https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=800&h=450&fit=crop&q=80',
    daw: 'Pro Tools',
    skill_level: 'Intermediate',
    category: 'Vocal Production',
    duration: '30 min',
    producer_id: 'p7',
    tags: ['pro tools', 'vocals', 'recording', 'comping', 'editing'],
    view_count: 72400,
    like_count: 5800,
    published_at: '2024-11-01T10:00:00Z',
    status: 'published',
  },
  {
    id: 't12',
    title: 'Phonk Production Masterclass: Memphis Rap Meets Modern Bass',
    slug: 'phonk-production-masterclass',
    excerpt: 'Dive into the world of phonk — learn the cowbell patterns, Memphis vocal chops, drifting 808s, and dark atmospheres that define the genre.',
    body: 'Full tutorial content here...',
    cover_image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=450&fit=crop&q=80',
    daw: 'FL Studio',
    skill_level: 'Master',
    category: 'Beat Making',
    duration: '40 min',
    producer_id: 'p9',
    tags: ['phonk', 'memphis', 'cowbell', '808', 'dark'],
    view_count: 345200,
    like_count: 28700,
    published_at: '2024-10-28T10:00:00Z',
    status: 'published',
  },
];

// ======================== BEATS DATA ========================

function generateWaveformData(length: number = 80): number[] {
  const data: number[] = [];
  for (let i = 0; i < length; i++) {
    const base = Math.sin(i * 0.15) * 0.3;
    const noise = Math.random() * 0.6;
    const envelope = Math.sin((i / length) * Math.PI) * 0.4;
    data.push(Math.min(1, Math.max(0.05, Math.abs(base + noise * envelope + 0.2))));
  }
  return data;
}

const beats = [
  {
    id: 'b1',
    title: 'Midnight Protocol',
    slug: 'midnight-protocol',
    producer_id: 'p1',
    bpm: 145,
    key: 'C minor',
    genre: 'Dark Trap',
    tags: ['dark', '808', 'hard', 'aggressive'],
    duration: '3:24',
    waveform_data: generateWaveformData(),
    plays: 45200,
    likes: 3400,
    cover_image: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=800&h=800&fit=crop&q=80',
    audio_url: null,
    is_featured: true,
    published_at: '2024-12-01T08:00:00Z',
    status: 'published',
  },
  {
    id: 'b2',
    title: 'Golden Hour',
    slug: 'golden-hour',
    producer_id: 'p2',
    bpm: 88,
    key: 'Ab major',
    genre: 'R&B',
    tags: ['smooth', 'keys', 'soulful', 'vibes'],
    duration: '4:12',
    waveform_data: generateWaveformData(),
    plays: 32100,
    likes: 2800,
    cover_image: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=800&h=800&fit=crop&q=80',
    audio_url: null,
    is_featured: true,
    published_at: '2024-11-30T08:00:00Z',
    status: 'published',
  },
  {
    id: 'b3',
    title: 'Drill Sergeant',
    slug: 'drill-sergeant',
    producer_id: 'p3',
    bpm: 140,
    key: 'F# minor',
    genre: 'Drill',
    tags: ['drill', 'UK', 'aggressive', 'bouncy'],
    duration: '2:58',
    waveform_data: generateWaveformData(),
    plays: 67800,
    likes: 5100,
    cover_image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=800&fit=crop&q=80',
    audio_url: null,
    is_featured: true,
    published_at: '2024-11-29T08:00:00Z',
    status: 'published',
  },
  {
    id: 'b4',
    title: 'Neon Dreams',
    slug: 'neon-dreams',
    producer_id: 'p4',
    bpm: 130,
    key: 'Eb minor',
    genre: 'Melodic Trap',
    tags: ['melodic', 'ambient', 'emotional', 'cinematic'],
    duration: '3:45',
    waveform_data: generateWaveformData(),
    plays: 89300,
    likes: 7200,
    cover_image: 'https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&h=800&fit=crop&q=80',
    audio_url: null,
    is_featured: true,
    published_at: '2024-11-28T08:00:00Z',
    status: 'published',
  },
  {
    id: 'b5',
    title: 'Subterranean',
    slug: 'subterranean',
    producer_id: 'p5',
    bpm: 150,
    key: 'G minor',
    genre: 'Phonk',
    tags: ['phonk', 'bass', 'heavy', 'drift'],
    duration: '2:36',
    waveform_data: generateWaveformData(),
    plays: 112400,
    likes: 9800,
    cover_image: 'https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=800&h=800&fit=crop&q=80',
    audio_url: null,
    is_featured: false,
    published_at: '2024-11-27T08:00:00Z',
    status: 'published',
  },
  {
    id: 'b6',
    title: 'Voltage Drop',
    slug: 'voltage-drop',
    producer_id: 'p6',
    bpm: 160,
    key: 'D minor',
    genre: 'Future Bass',
    tags: ['electronic', 'future bass', 'synths', 'drops'],
    duration: '3:18',
    waveform_data: generateWaveformData(),
    plays: 28900,
    likes: 2100,
    cover_image: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=800&h=800&fit=crop&q=80',
    audio_url: null,
    is_featured: false,
    published_at: '2024-11-26T08:00:00Z',
    status: 'published',
  },
  {
    id: 'b7',
    title: 'Vinyl Memoirs',
    slug: 'vinyl-memoirs',
    producer_id: 'p7',
    bpm: 92,
    key: 'Bb major',
    genre: 'Boom Bap',
    tags: ['sample', 'vinyl', 'classic', 'chill'],
    duration: '3:56',
    waveform_data: generateWaveformData(),
    plays: 54300,
    likes: 4600,
    cover_image: 'https://images.unsplash.com/photo-1461784180009-21121b2f204c?w=800&h=800&fit=crop&q=80',
    audio_url: null,
    is_featured: true,
    published_at: '2024-11-25T08:00:00Z',
    status: 'published',
  },
  {
    id: 'b8',
    title: 'Celestial Keys',
    slug: 'celestial-keys',
    producer_id: 'p8',
    bpm: 78,
    key: 'F major',
    genre: 'Gospel Trap',
    tags: ['keys', 'gospel', 'uplifting', 'spiritual'],
    duration: '4:32',
    waveform_data: generateWaveformData(),
    plays: 41200,
    likes: 3800,
    cover_image: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&h=800&fit=crop&q=80',
    audio_url: null,
    is_featured: false,
    published_at: '2024-11-24T08:00:00Z',
    status: 'published',
  },
  {
    id: 'b9',
    title: 'Shadow Realm',
    slug: 'shadow-realm',
    producer_id: 'p9',
    bpm: 155,
    key: 'A minor',
    genre: 'Dark Trap',
    tags: ['dark', 'eerie', 'horror', 'memphis'],
    duration: '2:48',
    waveform_data: generateWaveformData(),
    plays: 198700,
    likes: 16400,
    cover_image: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=800&h=800&fit=crop&q=80',
    audio_url: null,
    is_featured: true,
    published_at: '2024-11-28T08:00:00Z',
    status: 'published',
  },
  {
    id: 'b10',
    title: 'Rainy Window',
    slug: 'rainy-window',
    producer_id: 'p10',
    bpm: 72,
    key: 'C major',
    genre: 'Lo-Fi',
    tags: ['lo-fi', 'chill', 'study', 'rain'],
    duration: '5:10',
    waveform_data: generateWaveformData(),
    plays: 234100,
    likes: 19200,
    cover_image: 'https://images.unsplash.com/photo-1501426026826-31c667bdf23d?w=800&h=800&fit=crop&q=80',
    audio_url: null,
    is_featured: true,
    published_at: '2024-11-27T08:00:00Z',
    status: 'published',
  },
];

// ======================== GEAR REVIEWS DATA ========================

const gearReviews = [
  {
    id: 'g1',
    title: 'Akai MPC Live II Review: The Ultimate Standalone Beat Machine',
    slug: 'akai-mpc-live-ii-review',
    product: 'MPC Live II',
    brand: 'Akai Professional',
    category: 'Drum Machines',
    price: '$1,199',
    rating: 4.8,
    excerpt: "The MPC Live II is the best standalone beat machine ever made. Period. Here's why every producer needs one in their setup.",
    body: 'Full review content...',
    cover_image: 'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=800&h=450&fit=crop&q=80',
    pros: ['Standalone operation — no computer needed', '7" touchscreen with intuitive workflow', '16 velocity-sensitive pads feel incredible', 'Built-in speaker and rechargeable battery', 'Massive expansion storage via SATA drive'],
    cons: ['Heavy at 5.8 lbs for portability', 'Software updates can be slow', 'Learning curve for non-MPC users'],
    verdict: "The MPC Live II is the gold standard for standalone production. Whether you're on a plane, in a hotel, or in the studio, this machine delivers professional results.",
    affiliate_url: null,
    producer_id: 'p7',
    published_at: '2024-11-20T10:00:00Z',
    status: 'published',
  },
  {
    id: 'g2',
    title: 'Native Instruments Maschine MK3: Controller + Software Powerhouse',
    slug: 'native-instruments-maschine-mk3',
    product: 'Maschine MK3',
    brand: 'Native Instruments',
    category: 'Controllers',
    price: '$649',
    rating: 4.5,
    excerpt: 'Maschine MK3 bridges the gap between hardware and software like nothing else. But is the Komplete integration worth the price?',
    body: 'Full review content...',
    cover_image: 'https://images.unsplash.com/photo-1558383409-57baa6c8b082?w=800&h=450&fit=crop&q=80',
    pros: ['Komplete integration is unmatched', 'Dual high-res color displays', 'Smart Strip for note repeat and modulation', 'Excellent build quality and pad response', 'Massive sound library included'],
    cons: ['Requires computer to operate', 'Pricey compared to competitors', 'Can be overwhelming for beginners'],
    verdict: "If you're already in the NI ecosystem, Maschine MK3 is a no-brainer. The hardware-software integration is seamless and the sound library alone is worth the price.",
    affiliate_url: null,
    producer_id: 'p3',
    published_at: '2024-11-15T10:00:00Z',
    status: 'published',
  },
  {
    id: 'g3',
    title: "Yamaha HS8 Studio Monitors: Honest Sound at a Fair Price",
    slug: 'yamaha-hs8-studio-monitors',
    product: 'HS8',
    brand: 'Yamaha',
    category: 'Monitors',
    price: '$699/pair',
    rating: 4.6,
    excerpt: "The Yamaha HS8s continue the legacy of honest, flat monitoring. They won't flatter your mixes — and that's exactly the point.",
    body: 'Full review content...',
    cover_image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&h=450&fit=crop&q=80',
    pros: ['Incredibly flat frequency response', 'Excellent low-end for 8" woofer', 'Room control switches for acoustic correction', 'Built to last — classic Yamaha quality', 'White cone is iconic studio aesthetic'],
    cons: ['Can sound harsh in untreated rooms', 'Bass port noise at high volumes', 'Need proper placement for best results'],
    verdict: 'For producers who want truth over hype, the HS8s are the industry standard for a reason. Your mixes will translate better on every system.',
    affiliate_url: null,
    producer_id: 'p4',
    published_at: '2024-11-10T10:00:00Z',
    status: 'published',
  },
  {
    id: 'g4',
    title: 'Shure SM7B: The Vocal Mic That Changed Everything',
    slug: 'shure-sm7b-review',
    product: 'SM7B',
    brand: 'Shure',
    category: 'Microphones',
    price: '$399',
    rating: 4.9,
    excerpt: "From Michael Jackson's \"Thriller\" to every major podcast — the SM7B is the most versatile dynamic mic ever made. Here's our deep dive.",
    body: 'Full review content...',
    cover_image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&h=450&fit=crop&q=80',
    pros: ['Legendary vocal tone — warm, full, present', 'Excellent off-axis rejection', 'Built like a tank — will outlast you', 'Works for vocals, instruments, podcasts', 'Electromagnetic shielding kills hum/buzz'],
    cons: ['Needs a LOT of clean gain (CloudLifter recommended)', 'Heavy — need a sturdy boom arm', 'Not ideal for quiet acoustic sources'],
    verdict: "There's a reason the SM7B has been an industry staple for 50 years. Pair it with a CloudLifter and a good preamp, and you've got radio-ready vocals.",
    affiliate_url: null,
    producer_id: 'p1',
    published_at: '2024-11-05T10:00:00Z',
    status: 'published',
  },
  {
    id: 'g5',
    title: 'Universal Audio Apollo Twin X Review: Studio-Grade Interface',
    slug: 'universal-audio-apollo-twin-x',
    product: 'Apollo Twin X',
    brand: 'Universal Audio',
    category: 'Audio Interfaces',
    price: '$1,299',
    rating: 4.7,
    excerpt: 'The Apollo Twin X brings legendary UA preamps and real-time UAD processing to your desktop. Premium price, premium results.',
    body: 'Full review content...',
    cover_image: 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800&h=450&fit=crop&q=80',
    pros: ['Unison preamps sound incredible', 'Real-time UAD plugin processing', 'Near-zero latency monitoring', 'Premium build quality — all metal', 'Console software is intuitive and powerful'],
    cons: ['Expensive for a 2-input interface', 'UAD plugins require additional purchase', 'Thunderbolt only — no USB option'],
    verdict: 'If you can afford it, the Apollo Twin X is the best 2-channel interface money can buy. The Unison preamps and UAD ecosystem are game-changers.',
    affiliate_url: null,
    producer_id: 'p2',
    published_at: '2024-10-30T10:00:00Z',
    status: 'published',
  },
  {
    id: 'g6',
    title: 'Audio-Technica ATH-M50x: The Producer Headphone Standard',
    slug: 'audio-technica-ath-m50x',
    product: 'ATH-M50x',
    brand: 'Audio-Technica',
    category: 'Headphones',
    price: '$149',
    rating: 4.4,
    excerpt: 'At $149, the M50x might be the best value in studio headphones. Accurate, comfortable, and damn near indestructible.',
    body: 'Full review content...',
    cover_image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=450&fit=crop&q=80',
    pros: ['Outstanding accuracy for the price', 'Comfortable for long sessions', 'Detachable cables (3 included)', 'Folds flat for portability', 'Extended low-end for beat makers'],
    cons: ['Soundstage is narrow (closed-back)', 'Can get warm after 3+ hours', 'Earpads wear out and need replacement'],
    verdict: "The M50x remains the default recommendation for producers on a budget — and even producers NOT on a budget. Just buy them.",
    affiliate_url: null,
    producer_id: 'p5',
    published_at: '2024-10-25T10:00:00Z',
    status: 'published',
  },
  {
    id: 'g7',
    title: 'Novation Launchpad X: Grid Controller for Ableton Power Users',
    slug: 'novation-launchpad-x-review',
    product: 'Launchpad X',
    brand: 'Novation',
    category: 'MIDI Controllers',
    price: '$169',
    rating: 4.3,
    excerpt: 'The Launchpad X is the best grid controller for Ableton Live users. 64 RGB pads, velocity sensitivity, and deep DAW integration.',
    body: 'Full review content...',
    cover_image: 'https://images.unsplash.com/photo-1571266028243-d220c6d3173e?w=800&h=450&fit=crop&q=80',
    pros: ['Deep Ableton Live integration', 'Velocity and pressure-sensitive pads', 'RGB LED feedback is beautiful', 'Compact and bus-powered', 'Works with other DAWs via MIDI'],
    cons: ['Only really shines with Ableton', 'No knobs or faders', 'Pads are smaller than MPC-style'],
    verdict: 'For Ableton users, the Launchpad X is essential. For other DAW users, consider alternatives with more traditional controls.',
    affiliate_url: null,
    producer_id: 'p6',
    published_at: '2024-10-20T10:00:00Z',
    status: 'published',
  },
  {
    id: 'g8',
    title: 'Arturia MiniLab 3: Best Budget MIDI Keyboard for Beginners',
    slug: 'arturia-minilab-3-review',
    product: 'MiniLab 3',
    brand: 'Arturia',
    category: 'MIDI Controllers',
    price: '$99',
    rating: 4.2,
    excerpt: "Arturia's MiniLab 3 packs 25 keys, 8 pads, 8 knobs, and Analog Lab into a $99 package. Is it too good to be true?",
    body: 'Full review content...',
    cover_image: 'https://images.unsplash.com/photo-1552422535-c45813c61732?w=800&h=450&fit=crop&q=80',
    pros: ['Incredible value at $99', 'Analog Lab Intro included (500+ presets)', 'Slim, portable, USB-C', 'Knobs and pads add versatility', 'Works with any DAW'],
    cons: ['Mini keys — not for serious playing', 'No aftertouch', 'Pads are small and stiff'],
    verdict: 'For beginners and mobile producers, the MiniLab 3 is unbeatable value. The included Analog Lab software alone makes it worth the price.',
    affiliate_url: null,
    producer_id: 'p8',
    published_at: '2024-10-15T10:00:00Z',
    status: 'published',
  },
];

// ======================== SAMPLE PACKS DATA ========================

const samplePacks = [
  {
    id: 'sp1',
    title: 'Midnight 808 Kit Vol. 3',
    slug: 'midnight-808-kit-vol-3',
    creator: 'Bass Architect',
    price: 'Free',
    is_free: true,
    sample_count: 45,
    genres: ['Trap', 'Dark Trap', 'Phonk'],
    description: '45 carefully crafted 808 samples — from deep sub-bass to distorted aggression. Each tuned to C and ready to pitch.',
    cover_image: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=800&h=800&fit=crop&q=80',
    preview_sounds: [],
    rating: 4.9,
    download_count: 124500,
    published_at: '2024-11-28T10:00:00Z',
    status: 'published',
  },
  {
    id: 'sp2',
    title: 'Neo Soul Keys Collection',
    slug: 'neo-soul-keys-collection',
    creator: 'Nebula Keys',
    price: '$24.99',
    is_free: false,
    sample_count: 120,
    genres: ['R&B', 'Neo-Soul', 'Gospel'],
    description: 'Premium Rhodes, Wurlitzer, and Clavinet loops recorded through vintage tube amps. 120 loops in multiple keys and tempos.',
    cover_image: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800&h=800&fit=crop&q=80',
    preview_sounds: [],
    rating: 4.7,
    download_count: 34200,
    published_at: '2024-11-25T10:00:00Z',
    status: 'published',
  },
  {
    id: 'sp3',
    title: 'Drill Percussion Toolkit',
    slug: 'drill-percussion-toolkit',
    creator: 'DrumGod',
    price: '$14.99',
    is_free: false,
    sample_count: 200,
    genres: ['Drill', 'UK Drill', 'NY Drill'],
    description: '200 one-shot drum samples optimized for drill production. Includes slides, percs, hi-hats, snares, and kicks.',
    cover_image: 'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=800&h=800&fit=crop&q=80',
    preview_sounds: [],
    rating: 4.8,
    download_count: 87300,
    published_at: '2024-11-22T10:00:00Z',
    status: 'published',
  },
  {
    id: 'sp4',
    title: 'Lo-Fi Dreams Sample Pack',
    slug: 'lofi-dreams-sample-pack',
    creator: 'Luna Waves',
    price: 'Free',
    is_free: true,
    sample_count: 80,
    genres: ['Lo-Fi', 'Chill Hop', 'Jazz'],
    description: 'Vinyl textures, jazz piano loops, dusty drums, and ambient pads. Everything you need for lo-fi beats.',
    cover_image: 'https://images.unsplash.com/photo-1501426026826-31c667bdf23d?w=800&h=800&fit=crop&q=80',
    preview_sounds: [],
    rating: 4.6,
    download_count: 198400,
    published_at: '2024-11-18T10:00:00Z',
    status: 'published',
  },
  {
    id: 'sp5',
    title: 'Cinematic Strings & Pads',
    slug: 'cinematic-strings-pads',
    creator: 'Melo Circuit',
    price: '$29.99',
    is_free: false,
    sample_count: 65,
    genres: ['Melodic Trap', 'Cinematic', 'Ambient'],
    description: 'Orchestral strings and evolving pads perfect for melodic trap and cinematic production. Recorded with a 12-piece string section.',
    cover_image: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&h=800&fit=crop&q=80',
    preview_sounds: [],
    rating: 4.8,
    download_count: 45600,
    published_at: '2024-11-14T10:00:00Z',
    status: 'published',
  },
];

// ======================== ARTISTS DATA (TrapGlow) ========================

const artists = [
  {
    id: 'artist-1',
    name: 'Velvet Roux',
    slug: 'velvet-roux',
    real_name: 'Destiny Williams',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600',
    cover_image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1600',
    bio: "Velvet Roux emerged from Atlanta's underground scene with a voice that blends silk and fire. Her debut EP \"Midnight Honey\" fused neo-soul with trap production, earning comparisons to early SZA and Jhené Aiko. Now on her third project, she's carved out a lane that's entirely her own — lush harmonies over 808s, lyrics about self-worth and late-night drives through the city.",
    genre: ['R&B', 'Neo-Soul', 'Hip-Hop'],
    mood: ['Melodic', 'Dreamy', 'Late Night'],
    region: 'South',
    city: 'Atlanta, GA',
    social: { spotify: 'https://open.spotify.com/artist/velvetroux', instagram: 'https://instagram.com/velvetroux', twitter: 'https://twitter.com/velvetroux', tiktok: 'https://tiktok.com/@velvetroux', soundcloud: 'https://soundcloud.com/velvetroux' },
    spotify_embed: 'https://open.spotify.com/embed/track/4PTG3Z6ehGkBFwjybzWkR8',
    monthly_listeners: 284000,
    followers: 156000,
    glow_score: 94,
    glow_trend: 'rising',
    is_featured: true,
    is_daily_pick: true,
    featured_track: 'Satin Dreams',
    featured_track_url: null,
    tags: ['neo-soul', 'female-vocalist', 'atlanta', 'rising'],
    gallery: ['https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800', 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800', 'https://images.unsplash.com/photo-1501386761578-0a55d8b8dce7?w=800'],
    status: 'published',
  },
  {
    id: 'artist-2',
    name: 'Pharaoh Bliss',
    slug: 'pharaoh-bliss',
    real_name: 'Marcus Jordan',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
    cover_image: 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=1600',
    bio: "Pharaoh Bliss is Chicago's latest prodigy — a producer-rapper hybrid who builds his beats from scratch and then floats over them. His sound sits at the intersection of drill and jazz, sampling Coltrane over sliding 808s. He sold out Metro Chicago three times before ever releasing a full album.",
    genre: ['Hip-Hop', 'Drill', 'Alternative'],
    mood: ['Dark', 'Experimental', 'Aggressive'],
    region: 'Midwest',
    city: 'Chicago, IL',
    social: { spotify: 'https://open.spotify.com/artist/pharaohbliss', soundcloud: 'https://soundcloud.com/pharaohbliss', instagram: 'https://instagram.com/pharaohbliss', youtube: 'https://youtube.com/@pharaohbliss' },
    spotify_embed: 'https://open.spotify.com/embed/track/2Fxmhks0bxGSBdJ92vM42m',
    monthly_listeners: 512000,
    followers: 289000,
    glow_score: 97,
    glow_trend: 'rising',
    is_featured: true,
    is_daily_pick: false,
    featured_track: 'Gold Casket',
    featured_track_url: null,
    tags: ['drill', 'jazz-rap', 'chicago', 'producer'],
    gallery: ['https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=800', 'https://images.unsplash.com/photo-1598387181032-a3103a2db5b3?w=800'],
    status: 'published',
  },
  {
    id: 'artist-3',
    name: 'Luna Sage',
    slug: 'luna-sage',
    real_name: 'Selena Okafor',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600',
    cover_image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600',
    bio: "Nigerian-American singer Luna Sage fuses Afrobeats rhythms with indie pop sensibilities. Raised in Houston but rooted in Lagos, her music carries the weight of two worlds — amapiano-inspired grooves meet confessional songwriting. Her track \"Oshun's Daughter\" has 40M streams and counting.",
    genre: ['Afrobeats', 'Pop', 'Indie'],
    mood: ['Feel-Good', 'Melodic', 'Dreamy'],
    region: 'South',
    city: 'Houston, TX',
    social: { spotify: 'https://open.spotify.com/artist/lunasage', apple_music: 'https://music.apple.com/us/artist/luna-sage', instagram: 'https://instagram.com/lunasage', tiktok: 'https://tiktok.com/@lunasage' },
    apple_music_embed: 'https://embed.music.apple.com/us/album/oshuns-daughter/1234567890',
    monthly_listeners: 890000,
    followers: 430000,
    glow_score: 91,
    glow_trend: 'rising',
    is_featured: true,
    is_daily_pick: true,
    featured_track: "Oshun's Daughter",
    featured_track_url: null,
    tags: ['afrobeats', 'indie-pop', 'houston', 'nigerian'],
    gallery: ['https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800', 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800', 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800'],
    status: 'published',
  },
  {
    id: 'artist-4',
    name: 'KODA',
    slug: 'koda',
    real_name: 'Kofi Darko',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600',
    cover_image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1600',
    bio: "KODA doesn't follow trends — he sets them. The London-born, Toronto-raised artist pioneered a sound he calls \"neon trap\": futuristic synth work layered over hard-hitting drums with autotuned melodies that stick in your head for weeks. His debut album \"Signal Lost\" debuted at #14 on the Billboard 200.",
    genre: ['Trap', 'Electronic', 'Hip-Hop'],
    mood: ['Hype', 'Dark', 'Experimental'],
    region: 'Toronto',
    city: 'Toronto, ON',
    social: { spotify: 'https://open.spotify.com/artist/koda', soundcloud: 'https://soundcloud.com/kodamusic', instagram: 'https://instagram.com/koda', twitter: 'https://twitter.com/kodaofficial', youtube: 'https://youtube.com/@kodamusic' },
    spotify_embed: 'https://open.spotify.com/embed/track/3n3Ppam7vgaVa1iaRUc9Lp',
    soundcloud_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/koda-signal',
    monthly_listeners: 1240000,
    followers: 670000,
    glow_score: 99,
    glow_trend: 'rising',
    is_featured: true,
    is_daily_pick: false,
    featured_track: 'Signal Lost',
    featured_track_url: null,
    tags: ['neon-trap', 'toronto', 'electronic', 'billboard'],
    gallery: ['https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800', 'https://images.unsplash.com/photo-1598387181032-a3103a2db5b3?w=800', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800'],
    status: 'published',
  },
  {
    id: 'artist-5',
    name: 'Mira Voss',
    slug: 'mira-voss',
    real_name: 'Amira Vasquez',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600',
    cover_image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1600',
    bio: "Mira Voss brings the heat of Miami's Latin underground to the mainstream. Bilingual bars over reggaeton-trap fusions have made her the voice of a new generation. \"Fuego Lento\" spent 12 weeks on Spotify's Viral 50 chart, and her live shows are pure chaos — in the best way.",
    genre: ['Latin', 'Hip-Hop', 'Trap'],
    mood: ['Hype', 'Feel-Good', 'Aggressive'],
    region: 'South',
    city: 'Miami, FL',
    social: { spotify: 'https://open.spotify.com/artist/miravoss', apple_music: 'https://music.apple.com/us/artist/mira-voss', instagram: 'https://instagram.com/miravoss', tiktok: 'https://tiktok.com/@miravoss' },
    spotify_embed: 'https://open.spotify.com/embed/track/7GhIk7Il098yCjg4BQjzvb',
    monthly_listeners: 650000,
    followers: 380000,
    glow_score: 88,
    glow_trend: 'rising',
    is_featured: false,
    is_daily_pick: true,
    featured_track: 'Fuego Lento',
    featured_track_url: null,
    tags: ['latin-trap', 'bilingual', 'miami', 'viral'],
    gallery: ['https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800', 'https://images.unsplash.com/photo-1501386761578-0a55d8b8dce7?w=800'],
    status: 'published',
  },
  {
    id: 'artist-6',
    name: 'Onyx Saint',
    slug: 'onyx-saint',
    real_name: 'Damon Price',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600',
    cover_image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1600',
    bio: "Brooklyn's Onyx Saint raps like he's reading from a novel — dense, literary, and devastating. His storytelling ability draws comparisons to Nas and Black Thought, but his production choices — heavy on ambient textures and chopped samples — place him firmly in the future. \"Concrete Cathedral\" was named one of the best underground albums of the year by multiple outlets.",
    genre: ['Hip-Hop', 'Alternative', 'Neo-Soul'],
    mood: ['Emotional', 'Dark', 'Late Night'],
    region: 'East Coast',
    city: 'Brooklyn, NY',
    social: { spotify: 'https://open.spotify.com/artist/onyxsaint', soundcloud: 'https://soundcloud.com/onyxsaint', instagram: 'https://instagram.com/onyxsaint', twitter: 'https://twitter.com/onyxsaint' },
    spotify_embed: 'https://open.spotify.com/embed/track/0VjIjW4GlUZAMYd2vXMi3b',
    monthly_listeners: 175000,
    followers: 98000,
    glow_score: 82,
    glow_trend: 'rising',
    is_featured: false,
    is_daily_pick: false,
    featured_track: 'Concrete Cathedral',
    featured_track_url: null,
    tags: ['lyricist', 'brooklyn', 'underground', 'storytelling'],
    gallery: ['https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800', 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800'],
    status: 'published',
  },
  {
    id: 'artist-7',
    name: 'Zephyr Jones',
    slug: 'zephyr-jones',
    real_name: 'Zion Jones',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600',
    cover_image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1600',
    bio: "Zephyr Jones makes music for the golden hour. The Los Angeles-based producer-singer crafts hazy, sun-drenched soundscapes that blend lo-fi hip-hop with psychedelic soul. His instrumental mixtapes have become study session staples, but his vocal work reveals an artist with way more range than the algorithm suggests.",
    genre: ['Electronic', 'R&B', 'Alternative'],
    mood: ['Chill', 'Dreamy', 'Feel-Good'],
    region: 'West Coast',
    city: 'Los Angeles, CA',
    social: { spotify: 'https://open.spotify.com/artist/zephyrjones', soundcloud: 'https://soundcloud.com/zephyrjones', youtube: 'https://youtube.com/@zephyrjones', instagram: 'https://instagram.com/zephyrjones' },
    soundcloud_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/zephyr-golden',
    monthly_listeners: 420000,
    followers: 210000,
    glow_score: 78,
    glow_trend: 'steady',
    is_featured: false,
    is_daily_pick: false,
    featured_track: 'Golden Hour Drive',
    featured_track_url: null,
    tags: ['lo-fi', 'producer', 'la', 'psychedelic'],
    gallery: ['https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800', 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800'],
    status: 'published',
  },
  {
    id: 'artist-8',
    name: 'Sable Noir',
    slug: 'sable-noir',
    real_name: 'Isabelle Toure',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600',
    cover_image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1600',
    bio: "Sable Noir is the Paris-born, London-based singer redefining European R&B. Singing in English and French, she weaves between haunting ballads and dancefloor-ready UK garage reworkings. Vogue called her \"the future of transatlantic soul\" after her Glastonbury performance went viral.",
    genre: ['R&B', 'Electronic', 'Pop'],
    mood: ['Emotional', 'Melodic', 'Late Night'],
    region: 'UK',
    city: 'London, UK',
    social: { spotify: 'https://open.spotify.com/artist/sablenoir', apple_music: 'https://music.apple.com/us/artist/sable-noir', instagram: 'https://instagram.com/sablenoir', twitter: 'https://twitter.com/sablenoirmusic', tiktok: 'https://tiktok.com/@sablenoir' },
    spotify_embed: 'https://open.spotify.com/embed/track/1dGr1c8CrMLDpV6mPbImSI',
    monthly_listeners: 780000,
    followers: 410000,
    glow_score: 86,
    glow_trend: 'rising',
    is_featured: true,
    is_daily_pick: false,
    featured_track: 'Nuit Blanche',
    featured_track_url: null,
    tags: ['uk-rb', 'bilingual', 'london', 'garage'],
    gallery: ['https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800', 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800'],
    status: 'published',
  },
  {
    id: 'artist-9',
    name: 'RAE KAPITAL',
    slug: 'rae-kapital',
    real_name: 'Raymond Osei',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600',
    cover_image: 'https://images.unsplash.com/photo-1598387181032-a3103a2db5b3?w=1600',
    bio: "RAE KAPITAL brought rage music to the Afrobeats scene and nobody knew they needed it until they heard it. The Ghanaian-British rapper's aggressive delivery over Afro-drill production has created an entirely new subgenre. His track \"No Passport\" racked up 25M views on YouTube in its first month.",
    genre: ['Afrobeats', 'Drill', 'Hip-Hop'],
    mood: ['Aggressive', 'Hype', 'Dark'],
    region: 'UK',
    city: 'London, UK',
    social: { spotify: 'https://open.spotify.com/artist/raekapital', youtube: 'https://youtube.com/@raekapital', instagram: 'https://instagram.com/raekapital', twitter: 'https://twitter.com/raekapital' },
    spotify_embed: 'https://open.spotify.com/embed/track/5ghIgXAoN6qfbQ7lEDKLqR',
    monthly_listeners: 960000,
    followers: 520000,
    glow_score: 93,
    glow_trend: 'rising',
    is_featured: false,
    is_daily_pick: true,
    featured_track: 'No Passport',
    featured_track_url: null,
    tags: ['afro-drill', 'ghanaian', 'rage', 'london'],
    gallery: ['https://images.unsplash.com/photo-1598387181032-a3103a2db5b3?w=800', 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=800'],
    status: 'published',
  },
  {
    id: 'artist-10',
    name: 'Cypress Ray',
    slug: 'cypress-ray',
    real_name: 'Cypress Raymond',
    avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=600',
    cover_image: 'https://images.unsplash.com/photo-1501386761578-0a55d8b8dce7?w=1600',
    bio: "Cypress Ray is country-trap's most unlikely champion — a former church choir singer from rural Louisiana who blends twangy guitars with 808s and Auto-Tune. What sounds like it shouldn't work absolutely does. His debut single \"Bayou Gospel\" earned a cosign from T-Pain and has redefined what Southern rap can sound like.",
    genre: ['Hip-Hop', 'Alternative', 'Trap'],
    mood: ['Feel-Good', 'Emotional', 'Melodic'],
    region: 'South',
    city: 'Baton Rouge, LA',
    social: { spotify: 'https://open.spotify.com/artist/cypressray', instagram: 'https://instagram.com/cypressray', tiktok: 'https://tiktok.com/@cypressray' },
    spotify_embed: 'https://open.spotify.com/embed/track/2LBqCSwhJGcFQeTHnhEN6u',
    monthly_listeners: 340000,
    followers: 180000,
    glow_score: 76,
    glow_trend: 'new',
    is_featured: false,
    is_daily_pick: false,
    featured_track: 'Bayou Gospel',
    featured_track_url: null,
    tags: ['country-trap', 'louisiana', 'southern', 'church'],
    gallery: ['https://images.unsplash.com/photo-1501386761578-0a55d8b8dce7?w=800'],
    status: 'published',
  },
];

// ======================== ROUTE HANDLER ========================

export async function POST() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceKey) {
    return NextResponse.json({ error: 'Missing Supabase env vars' }, { status: 500 });
  }

  const supabase = createClient(supabaseUrl, serviceKey);
  const results: Record<string, { count: number; error?: string }> = {};

  try {
    // 1. Upsert producers
    const producerData = producers.map(p => ({
      ...p,
      avatar: p.avatar || FALLBACK_IMAGES.producerAvatar,
      cover_image: p.cover_image || FALLBACK_IMAGES.producerCover,
    }));
    const { error: producerError, data: producerResult } = await supabase
      .from('producers')
      .upsert(producerData, { onConflict: 'id' });
    results.producers = { count: producerData.length, error: producerError?.message };

    // 2. Upsert tutorials
    const tutorialData = tutorials.map(t => ({
      ...t,
      cover_image: t.cover_image || FALLBACK_IMAGES.tutorialCover,
    }));
    const { error: tutorialError } = await supabase
      .from('tutorials')
      .upsert(tutorialData, { onConflict: 'id' });
    results.tutorials = { count: tutorialData.length, error: tutorialError?.message };

    // 3. Upsert beats
    const beatData = beats.map(b => ({
      ...b,
      cover_image: b.cover_image || FALLBACK_IMAGES.beatCover,
    }));
    const { error: beatError } = await supabase
      .from('beats')
      .upsert(beatData, { onConflict: 'id' });
    results.beats = { count: beatData.length, error: beatError?.message };

    // 4. Upsert gear reviews
    const gearData = gearReviews.map(g => ({
      ...g,
      cover_image: g.cover_image || FALLBACK_IMAGES.gearCover,
    }));
    const { error: gearError } = await supabase
      .from('gear_reviews')
      .upsert(gearData, { onConflict: 'id' });
    results.gear_reviews = { count: gearData.length, error: gearError?.message };

    // 5. Upsert sample packs
    const packData = samplePacks.map(sp => ({
      ...sp,
      cover_image: sp.cover_image || FALLBACK_IMAGES.samplePackCover,
    }));
    const { error: packError } = await supabase
      .from('sample_packs')
      .upsert(packData, { onConflict: 'id' });
    results.sample_packs = { count: packData.length, error: packError?.message };

    // 6. Upsert artists
    const artistData = artists.map(a => ({
      ...a,
      avatar: a.avatar || FALLBACK_IMAGES.artistAvatar,
      cover_image: a.cover_image || FALLBACK_IMAGES.artistCover,
    }));
    const { error: artistError } = await supabase
      .from('artists')
      .upsert(artistData, { onConflict: 'id' });
    results.artists = { count: artistData.length, error: artistError?.message };

    const hasErrors = Object.values(results).some(r => r.error);
    return NextResponse.json({
      success: !hasErrors,
      results,
      message: hasErrors ? 'Some tables had errors' : 'All data seeded successfully',
    }, { status: hasErrors ? 207 : 200 });

  } catch (err: any) {
    return NextResponse.json({
      success: false,
      error: err.message,
      results,
    }, { status: 500 });
  }
}

export async function GET() {
  return NextResponse.json({
    message: 'POST to this endpoint to seed content data into Supabase',
    tables: ['producers', 'tutorials', 'beats', 'gear_reviews', 'sample_packs', 'artists'],
  });
}
